### ISSUE TITLE
Question: intellisense/autocomplete on @use

### ISSUE THREAD

**Issue by Vassi** [TheRealSyler/vscode-sass-indented#64]
This is maybe more of a question. Is this extension intended to provide auto-complete support for @use declarations? I'm also maybe wondering if it's a weird config issue.

Context: I'm using a create-react-app setup with sass (dart-sass) package for compilation. I can successfully use the following:

```scss
// shared/styles/_variables.scss
$html-font-size: 16px;

// shared/styles/_mixins.scss
@use 'variables' as vars;

@function stripUnit($value) {
  @return $value / ($value * 0 + 1);
}

@function asRem($pxValue) {
  @return #{stripUnit($pxValue) / stripUnit(vars.$html-font-size)}rem;
}

// shared/layout/navLayout.module.scss
@use 'shared/styles/mixins' as mixins;

.navContainer {
  display: flex;
  position: absolute;
  top:0px;
  left:0px;
  right:0px;
  height: mixins.asRem(50px);
  align-items:center;
}
```

This compiles and works, but I get no auto-complete for `vars.` in mixins, and nothing for `mixins.` in navLayout. I was wondering if I have to set some kind of SASS_IMPORTS path or if use just isn't supported the way I think it is?
