### ISSUE TITLE
Meta property value was not fully recognized

### ISSUE THREAD

**Issue by edumqssan** [TheRealSyler/vscode-sass-indented#92]
**Describe the bug**
Part of syntax highlighting of meta.property-value mistaken as support.constant.mathematical-symbols

**To Reproduce**
Create a file .scss and add the following code:
```scss
code { 

font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;

}
```

**Expected behavior**
When add the source-code-pro **without quotation** in .css, the editor recognizes the symbol as part of meta.property-value
```css
code { 

font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;

}
```

**Screenshots**
> On VS Code version 1.62.3

The SCSS file showing meta property value was not fully recognized:
![Capture1](https://user-images.githubusercontent.com/56772885/144892166-faf828c8-e6be-45b1-a9de-e272ceea0d32.JPG)
CSS file showing meta property value being fully recognized:
![Capture2](https://user-images.githubusercontent.com/56772885/144892454-50b1d674-d081-46a1-aa75-5b18e13db773.JPG)

**Additional context**
Not sure what is the implications for this to happen, but as it did not happen on *.css files, I believed it could be a bug.
