### ISSUE TITLE
Syntax error reported when using `@at-rule` with/without syntax.

### ISSUE THREAD

**Issue by JoshuaSand0val** [TheRealSyler/vscode-sass-indented#97]
**Describe the bug**
Whenever using the `@at-root` syntax to exclude certain media query features, VS Code reports a syntax error when there is not one.

**To Reproduce**
Copy the code attached below, or write a simple `@at-root` declaration using the with/without syntax.
If you are just recently aware of this feature as I was, documentation here:
https://sass-lang.com/documentation/at-rules/at-root#beyond-style-rules

**Expected behavior**
No error being reported.

**Screenshots**

<img width="185" alt="image" src="https://user-images.githubusercontent.com/22820141/158485709-f2a683d3-9fb0-456a-80c8-3ee70b540bc4.png">

```scss
.at-root-without {
    @at-root (without: media) {
        color: red;
    }
}
```
